name: EPG Update

on:
  push:
  schedule:
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: EPG Update
      run: |
        rm -f 对应表.xlsx External.m3u 
        rm -f e.xml && wget https://epg.112114.xyz/pp.xml -O epg.xml
        git config --global user.name tslatop
        git config --global user.email tslatop@gmail.com
        git add e.xml
        git commit -m "Update e.xml"
        git push -f origin main
